apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambassador

commonLabels:
  app.kubernetes.io/name: ambassador

bases:
  - ../prod/

patchesStrategicMerge:
  - patches/issuer.yaml
  - patches/deployment.yaml

resources:
  - resources/mappings/k7o-io.yaml
