apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambassador

commonLabels:
  app.kubernetes.io/name: ambassador

bases:
  - ../base/

configMapGenerator:
  - name: oathkeeper-config
    behavior: replace
    files:
      - configs/oathkeeper/config.yaml
      - configs/oathkeeper/rules.yaml

patchesStrategicMerge:
  - patches/authservice.yaml
  - patches/service.yaml

resources:
  - resources/issuers/selfsigned.yaml
  - resources/certificates/ca.yaml
  - resources/issuers/ca.yaml
  - resources/certificates/k7o-io.yaml
  - resources/host.yaml
  - resources/mappings/httpbin.yaml
