# https://www.getambassador.io/docs/latest/topics/running/services/auth-service/

apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: ambassador
spec:
  allowed_authorization_headers:
    - X-User
