apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambassador

commonLabels:
  app.kubernetes.io/name: ambassador

bases:
  - ../base/

configurations:
  - configuration.yaml

configMapGenerator:
  - name: oathkeeper-config
    behavior: replace
    files:
      - configs/oathkeeper/config.yaml
      - configs/oathkeeper/rules.yaml

secretGenerator:
  - name: route53-credentials
    env: configs/route53-credentials.env

patchesStrategicMerge:
  - patches/authservice.yaml
  - patches/deployment.yaml

resources:
  - resources/domains/issuer.yaml
  - resources/domains/k7o.io/certificate.yaml
  - resources/domains/k7o.io/host.yaml
