# https://www.getambassador.io/docs/latest/topics/running/services/auth-service/

apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: ambassador
spec:
  auth_service: http://localhost:4456
  path_prefix: /decisions
  timeout_ms: 1000
  status_on_error:
    code: 503
