apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - secrets
      - endpoints
    verbs: [get, list, watch]

  - apiGroups: [getambassador.io]
    resources: ["*"]
    verbs: [get, list, watch, update, patch, create, delete]

  - apiGroups: [apiextensions.k8s.io]
    resources:
      - customresourcedefinitions
    resourceNames:
      - authservices.getambassador.io
      - mappings.getambassador.io
      - modules.getambassador.io
      - ratelimitservices.getambassador.io
      - tcpmappings.getambassador.io
      - tlscontexts.getambassador.io
      - tracingservices.getambassador.io
      - kubernetesendpointresolvers.getambassador.io
      - kubernetesserviceresolvers.getambassador.io
      - consulresolvers.getambassador.io
      - filters.getambassador.io
      - filterpolicies.getambassador.io
      - ratelimits.getambassador.io
      - hosts.getambassador.io
      - logservices.getambassador.io
    verbs: [get, list, watch, delete]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]

  - apiGroups: [networking.internal.knative.dev]
    resources: [clusteringresses]
    verbs: [get, list, watch]

  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch]

  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses/status]
    verbs: [update]
