apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
spec:
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        linkerd.io/inject: enabled
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ambassador
      containers:
        - name: ambassador
          image: datawire/ambassador
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [all]
            privileged: false
            runAsUser: 8888
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: http-admin
              containerPort: 8877
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: http-admin
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: http-admin
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: ambassador-pod-info
              mountPath: /tmp/ambassador-pod-info
              readOnly: true
        - name: oathkeeper
          image: oryd/oathkeeper
          args:
            - serve
            - --disable-telemetry
            - --sqa-opt-out
            - --config=/etc/oathkeeper/config.yaml
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [all]
            privileged: false
            readOnlyRootFilesystem: true
          ports:
            - name: http-ok-api
              containerPort: 4456
            - name: http-ok-metric
              containerPort: 9000
          readinessProbe:
            httpGet:
              port: http-ok-api
              path: /health/ready
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-ok-api
              path: /health/alive
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: empty
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: oathkeeper-config
              mountPath: /etc/oathkeeper/
              readOnly: true
      volumes:
        - name: ambassador-pod-info
          downwardAPI:
            items:
              - fieldRef:
                  fieldPath: metadata.labels
                path: labels
        - name: empty
          emptyDir: {}
        - name: oathkeeper-config
          configMap:
            name: oathkeeper-config
