# https://www.getambassador.io/docs/latest/topics/running/ambassador/

apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    add_linkerd_headers: true
    envoy_log_type: json
    gzip:
      enabled: true
    # server_name: "x"
