# https://www.ory.sh/oathkeeper/docs/reference/configuration/

access_rules:
  repositories:
    - file:///etc/oathkeeper/rules.yaml

log:
  format: json

authenticators: {}
authorizers: {}
mutators: {}
