name: CI/CD

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ctison/actions/conftest@master
      - uses: ctison/actions/k3d@master
      - uses: ctison/actions/kustomize@master
      - uses: actions/checkout@v2
        with:
          repository: ctison/cert-manager
          path: cert-manager
      # - name: Setup test cluster
      #   run: |
      #     make cluster-create
      #     make -C cert-manager install K8Z=staging
      # - name: Test
      #   if: github.ref != 'refs/heads/master'
      #   run: make install test-dev
      - name: Setup credentials
        if: github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_HOSTED_ZONE_ID: ${{secrets.AWS_HOSTED_ZONE_ID}}
          ROUTE53_CREDENTIALS: ${{secrets.ROUTE53_CREDENTIALS}}
        run: |
          sed -Ei "s/(^ +accessKeyID: ).+$/\1$AWS_ACCESS_KEY_ID/" prod/resources/domains/issuer.yaml
          sed -Ei "s/(^ +hostedZoneID: ).+$/\1$AWS_HOSTED_ZONE_ID/" prod/resources/domains/issuer.yaml
          echo "$ROUTE53_CREDENTIALS" > prod/configs/route53-credentials.env
      # - name: Test staging
      #   if: github.ref == 'refs/heads/master'
      #   run: make install K8Z=staging test-staging
      - name: Deploy to staging
        if: github.ref == 'refs/heads/master'
        env:
          K8S_STAGING: ${{secrets.K8S_STAGING}}
        run: |
          echo "$K8S_STAGING" > kubeconfig
          KUBECONFIG="$PWD/kubeconfig" make install K8Z=prod
          rm kubeconfig
